_target_: chunkgfn.datamodules.bit_sequence.BitSequenceModule

max_len: 32
num_train_iterations: 100
sample_exact_length: True # Whether to always sample sequences of length `max_len` or not
threshold: 8 # Threshold leveinstein distance for mode discovery
output_padding_mask: False
batch_size: 32
num_workers: 0
pin_memory: True
persistent_workers: False