_target_: chunkgfn.environment.selfies_sequence.SELFIESSequenceModule

max_len: 32
num_train_iterations: 100
sample_exact_length: False
batch_size: 64
num_workers: 0
pin_memory: True
persistent_workers: False