# https://hydra.cc/docs/configure_hydra/intro/

# enable color logging
defaults:
  - override hydra_logging: colorlog
  - override job_logging: colorlog

# output directory, generated dynamically on each run
run:
  dir: ${paths.log_dir}/${task_name}/runs/${logger.wandb.id}
sweep:
  dir: ${paths.log_dir}/${task_name}/multiruns/${logger.wandb.id}
  subdir: ${hydra.job.num}