all_libs=(
    "A,C,G,U,GG,GGGG,CC,CCCC,GCCCC,GGGGGCCCC,GC,GCGGGGGCCCC,GCC,GCGGGGGCCCCGC,GCGGGGGCCCCGCG,GCGGGGGCCCCGCA,GCGGGGGCCCCGCC,GCGGGGGCCCCGCU,GGGGGCCCCGC,GCGCGGGGGCCCC,GGGGGCCCCGCGC,GGGGGCCCCGCGCG,GCGCGGGGGCCCCG,GGGGGCCCCGCGCC,GGGGGCCCCGCGCU,GGGGGCCCCGCGCA,GCGCGGGGGCCCCA,GCGCGGGGGCCCCC"
    "A,C,G,U,GCGCGGGGGCCCCU,GCGCGGGGGCCCCG,GGU,GCGGGGGCCCCGCU,CGCGGGGGCCCCGC,GUGCGGGGGCCCCU,CGCGCGGGGGCCCC,GGC,GGGG,GCGGGGGCCCCGCG,GCGCGCGGGGGCC,GGGGGCCCCGCGCG,CCGCGCGGGGGCCC,GGGGGCCCCGCGCA,GGGGGCCCCGCGCU,GGGGGG,GGGGGCCCCGCGCC,GCGGGGGCCCC,GGGGGCCCCGCGUG,GCGCGGGGGCCCU,GCGCGGGGGCC,GCC,GUGCGGGGGCCCCG,GCGCGGGGGCCCCC,GCGGGGGCCCCGCA"
    "A,C,G,U,GG,GGGG,GGGGGGGG,GGGGGGGGGGGG,GGGGGG,GC,CGGGG,GGGGGGGGGGGGGC,GGGC,GU,GCGGGGGGGGGGGG,GCGGGGGGGG,GGGGGGGGCGGGG,CGG,GGGGGC,CC,GGGGGGGGCGGGGC,GGGGC,GGGGGGGGCGGGGU,GGGGGGGGCGGGGG,CGGGGGGGG,GGGGGGGGCGGGGA,ACGGGG,CGGGGGGGGCGGGG"
    "A,C,G,U,GGCGGGGGGCGGGG,GGCGGGGGGGGGGG,GCGGGGGGGGGGCG,GGGGGGGGGGGGGU,GGGGCGGGGGGGG,CGGGG,GGGGC,GGGGGGGGGGGGGG,GGCG,GGGCGGGGGGGGG,GGGGGGGGGCGGGC,GG,CGGGCGGGGGGGG,GCGGGGGGGGGGGU,GGCGGGGGGGG,GGGGGG,GGGU,GGU,CGGGC,GCGGGGGGG,GCGGGGGGGGGGGG,GGGGGGGGGGGGCG,GGGGGGGGGGGGG,GGGCGGGGGGGG,GCGGGCGGGGGGGG"
    "A,C,G,U,GG,GGGG,GC,GCGGGG,GGC,CC,GCGGGGGC,CCC,GCC,GCGGGGGCC,GCGGGGGCCCC,GCGGGGGCCC,GCGCGGGGGCCCC,GGCGCGGGGGCCCC,GCGGGGGCCCCGCC,GCGGGGGCCCCGC,GCGGGGGCCCCGCA,GCGCGGGGGCCCCG,GCGCGGGGGCCCCA,GCGGGGGCCCCGCG,CCCC,CGCGCGGGGGCCCC,GGCGGGG,GCCC"
    "A,C,G,U,GCC,GCGCGGGGGCCUAU,GCGGGGGCC,GCGCGGGGGCCCCC,GCGGGGGCCCCGCA,GCGCGGGGGCCU,GC,CC,GCGCGGGGGCCCUG,GCGCGGGGGCCCCG,GGC,GGGGGCC,GCGCGGGGGCCUAG,CGC,GCGGGGGCCCC,GGGG,GCGGGGGCCCCGCG,GCGGGG,GCGCGGGGGCCCCA,GCCCCCC,GCGCGGGGGCC,GCGCGGGGGCCUAA,CU"
    "A,C,G,U,GG,CC,GC,GGGG,GCC,GU,GGGGGCC,CU"
    "A,C,G,U,GGU,GCGCGGGGGCCCC,GCGGGGGCCCCGC,CGCGGGGGCCCCGC,GGGGGCC,GCGGGGGCCCCGU,CC,AA,UC,GGGGGCCCCGCGCU,GCGG,AU,GGGGGCCCC,GCCC,GGC,GCGGGGGCCCC,GGGGGCCCCGCGC,GCG,GGGGGCCCCGCGU,GCGGGGGCCCCGGC,AC,GAC,CCC,CU,GGGU"
    "A,C,G,U,GG,CC,GC,GGGG,GCC,GU,GGGGGCC,CU"
    "A,C,G,U,GUA,GCU,GGGCC,GGU,CGCGGGGGCCCCGC,GGGGGCCCC,UC,UA,GCGGGGGCCCC,UGG,CGU,GA,UCC,GCGU,GGGGGCCCCGC,GCCCC,GCGG,GGCGCGGGGGCCCC,CGCGCGGGGGCCCC,GCGCGGGGGCCCCA,GCG,GGCC,GUCC,GGC,CGGGG"
    "A,C,G,U,GG,CC,GC,GGGG,GCC,GU,GGGGGCC,GCGC"
    "A,C,G,U,CCCC,GCGC,GCGCGGGGGCCCC,CGCC,GA,GCGG,GGGGGCCCCGC,CGG,GCU,CU,GGCC,CGCGCGGGGGCCCU,GUCC,CGU,GCA,GGGG,CA,GGGGGCCCCGCGC,GCGCGGGGGCC,GCGCGGGGGCCCCG,CGC,GC,AA,GU,GCGGGGGCCCCGC"
)

tasks=(
    L14_RNA1
    L14_RNA2
    L14_RNA3
)



# Function to format list for Hydra CLI
format_for_hydra() {
    local items=$1
    echo "environment.actions=[${items}]"
}


for seed in 1998 2024 42
do
    for lib in "${all_libs[@]}"
    do
        for task in "${tasks[@]}"
        do
            hydra_arg=$(format_for_hydra "$lib")
            sbatch sbatch_scripts/rna_binding/rna_binding.sh \
            experiment=rna_prioritized \
            task_name=rna_binding \
            environment.task=${task} \
            environment.output_padding_mask=False \
            environment.modes_path="${HOME}/Chunk-GFN/${task}_modes.pickle" \
            environment.dataset_path="${HOME}/Chunk-GFN/${task}_dataset.pickle" \
            seed=${seed} \
            algo.replay_buffer.cutoff_distance=3 \
            algo.reward_temperature=0.1 \
            algo.partition_init=11 \
            logger.wandb.name=rna_prioritized_${task}_downstream \
            logger.wandb.group=rna_binding \
            $hydra_arg
        done 
    done
done
