# https://wandb.ai

wandb:
  _target_: lightning.pytorch.loggers.wandb.WandbLogger
  name: ${oc.env:SLURM_JOB_NAME}_${oc.env:SLURM_JOB_ID}
  save_dir: "${paths.output_dir}"
  offline: False
  id: ${oc.env:SLURM_JOB_ID} # pass correct id to resume experiment!
  anonymous: null # enable anonymous logging
  project: "gfn-chunking"
  log_model: False # upload lightning ckpts
  prefix: "" # a string to put at the beginning of metric keys
  # entity: "" # set to name of your wandb team
  group: ""
  tags: []
  job_type: ""
  resume: allow # This allows resuming when the job is requeued